# Generated by Django 4.2.7 on 2024-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_alter_task_options_alter_task_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Добавить в избранное'),
        ),
    ]
